### ISSUE TITLE
Connection refuse, reason code : 5

### ISSUE THREAD

**Issue by K-YSoftware** [tuanpmt/esp32-mqtt#13]
[MQTT INFO] Resolve dns for domain: geeknesia.com
[MQTT INFO] Connecting to server 207.46.228.57:8883,45858
[MQTT INFO] Creating SSL object...
[MQTT INFO] Start SSL connect..
[MQTT INFO] Connected!
[MQTT INFO] Connected to server geeknesia.com:8883
[MQTT INFO] Sending MQTT CONNECT message, type: 1, id: 0000
[MQTT INFO] Reading MQTT CONNECT response message
[MQTT WARN] Connection refuse, reason code: 5
[MQTT INFO] Resolve dns for domain: geeknesia.com
[MQTT INFO] Connecting to server 207.46.228.57:8883,45858
[MQTT INFO] Creating SSL object...
[MQTT INFO] Start SSL connect..
[MQTT INFO] Connected!
[MQTT INFO] Connected to server geeknesia.com:8883
[MQTT INFO] Sending MQTT CONNECT message, type: 1, id: 0000
[MQTT INFO] Reading MQTT CONNECT response message
[MQTT WARN] Connection refuse, reason code: 5
[MQTT INFO] Resolve dns for domain: geeknesia.com
[MQTT INFO] Connecting to server 207.46.228.57:8883,45858
[MQTT INFO] Creating SSL object...
[MQTT INFO] Start SSL connect..
[MQTT INFO] Connected!
[MQTT INFO] Connected to server geeknesia.com:8883
[MQTT INFO] Sending MQTT CONNECT message, type: 1, id: 0000
[MQTT INFO] Reading MQTT CONNECT response message
[MQTT WARN] Connection refuse, reason code: 5
[MQTT INFO] Resolve dns for domain: geeknesia.com
[MQTT INFO] Connecting to server 207.46.228.57:8883,45858
[MQTT INFO] Creating SSL object...
[MQTT INFO] Start SSL connect..
I (12994) wifi: pm start, type:0

**Comment by tuanpmt** [comment]
```
5 | 0x05 Connection Refused, not authorized | The Client is not authorized to connect
```
